### ISSUE TITLE
Update ionic to v1.2

### ISSUE THREAD

**Issue by skounis** [skounis/supermodular#34]
We should proceed with all the adjustments in the code in order to adopt and demonstrate Ionic 1.2 changes and features.

Tasks / Goals
- [x] Code and project structure adjustments #35
- [x] Demonstration of Native Scrolling #36
- [x] Demonstration of New Slide Box #37
